### ISSUE TITLE
まとめissue: 2020年小学校学習指導要領関連リソースを追加（2020年度使用教科書登録関連）

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#460]
2020年度、小学校の使用教科書から、新しい指導要領になるため、いつもよりたくさんすることがあるので、まとめissueを作っておく。
一つ一つは、それぞれissueを立てて運用する。
思いついたものをリストアップしておく。

注：今年度最低限いるのは、小学校の分だけだが、作業の都合上、一緒にしてもよさそうなものは、それぞれのissueは中学校と高等学校の分もはいっていることがある。

- [x] curriculum-*.ttl 2020年度小学校学習指導要領リソースの作成　（注： #413 で既に追加済み）
- [x] subjectArea-*.ttl 教科リソースの作成  (2020年度、小学校の使用教科書分) #461
- [x] subject-*.ttl 種目リソースの作成 (2020年度、小学校の使用教科書分) #462 
- [x] catalogue-*.ttl 教科書目録リソースの作成 (2020年度、小学校の使用教科書分) #463
- [x] publisher-*.ttl 2020年度使用教科書目録の出版者情報リソースの作成 #465
- [x] textbook-*.ttl 教科書リソースの作成 (2020年度、小学校の使用教科書分) #470
- [x] subjectType-*.ttl 教科・種目種別をあらわすリソースの作成（高校のみ関連）  #467 （高校のみ関連なので、今回じゃなくてもいいが、小・中・高と一度に作った関係上ここに入れとく）
- [x] トップページに新学習指導要領を追加 #479

**Comment by masao** [comment]
一通り終わりにしてよいと思います。
→ Version 16.0 リリースします。

**Comment by yegusa** [comment]
教科書の書誌データ本体がまだですので、これは残しとく？

**Comment by yegusa** [comment]
全部、チェックできたのでクローズします。
